/*
  Do not edit directly, this file was auto-generated.
*/

package com.infomaniak.designsystem.swisstransfer.internal

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.foundation.BorderStroke
import androidx.compose.ui.graphics.shadow.Shadow

import com.infomaniak.designsystem.primitivetokens.*

internal object IntermediateSwisstransferLight {
  val BlurNone: Dp = Blur0
  val BlurXs: Dp = Blur4
  val BlurSm: Dp = Blur8
  val BlurMd: Dp = Blur12
  val BlurLg: Dp = Blur16
  val BlurXl: Dp = Blur24
  val Blur2xl: Dp = Blur40
  val Blur3xl: Dp = Blur64
  val BorderNoneWidth: Dp = BorderWidth0
  val BorderXsWidth: Dp = BorderWidth1
  val BorderSmWidth: Dp = BorderWidth2
  val BorderMdWidth: Dp = BorderWidth3
  val BorderLgWidth: Dp = BorderWidth4
  val ColorBackgroundElevationSurfacePressed: Color = ColorGray100
  val ColorBackgroundElevationSurfaceHover: Color = ColorGray50
  val ColorBackgroundElevationSurfaceDefault: Color = ColorWhite
  val ColorBackgroundElevationSurfaceSelected: Color = ColorGray200
  val ColorBackgroundElevationOverlayDefault: Color = ColorGray100
  val ColorBackgroundElevationOverlayHover: Color = ColorGray200
  val ColorBackgroundElevationOverlayPressed: Color = ColorGray300
  val ColorBackgroundElevationOverlaySelected: Color = ColorGray400
  val ColorBackgroundElevationRaisedDefault: Color = ColorWhite
  val ColorBackgroundElevationRaisedHover: Color = ColorGray50
  val ColorBackgroundElevationRaisedPressed: Color = ColorGray100
  val ColorBackgroundElevationRaisedSelected: Color = ColorGray200
  val ColorBackgroundElevationSunkenPressed: Color = ColorGray300
  val ColorBackgroundElevationSunkenHover: Color = ColorGray200
  val ColorBackgroundElevationSunkenDefault: Color = ColorGray100
  val ColorBackgroundElevationSunkenSelected: Color = ColorGray400
  val ColorBackgroundFeedbackErrorDim1Default: Color = ColorRed500
  val ColorBackgroundFeedbackErrorDim1Hover: Color = ColorRed600
  val ColorBackgroundFeedbackErrorDim1Pressed: Color = ColorRed700
  val ColorBackgroundFeedbackErrorDim2Default: Color = ColorRed200
  val ColorBackgroundFeedbackErrorDim2Hover: Color = ColorRed300
  val ColorBackgroundFeedbackErrorDim2Pressed: Color = ColorRed400
  val ColorBackgroundFeedbackWarningDim1Default: Color = ColorOrange400
  val ColorBackgroundFeedbackWarningDim1Hover: Color = ColorOrange500
  val ColorBackgroundFeedbackWarningDim1Pressed: Color = ColorOrange600
  val ColorBackgroundFeedbackWarningDim2Default: Color = ColorOrange200
  val ColorBackgroundFeedbackWarningDim2Hover: Color = ColorOrange300
  val ColorBackgroundFeedbackWarningDim2Pressed: Color = ColorOrange400
  val ColorBackgroundFeedbackSuccessDim1Default: Color = ColorLime500
  val ColorBackgroundFeedbackSuccessDim1Hover: Color = ColorLime600
  val ColorBackgroundFeedbackSuccessDim1Pressed: Color = ColorLime700
  val ColorBackgroundFeedbackSuccessDim2Default: Color = ColorLime200
  val ColorBackgroundFeedbackSuccessDim2Hover: Color = ColorLime300
  val ColorBackgroundFeedbackSuccessDim2Pressed: Color = ColorLime400
  val ColorBackgroundBrandInfomaniakDefault: Color = ColorBlue500
  val ColorBackgroundBrandInfomaniakHover: Color = ColorBlue600
  val ColorBackgroundBrandInfomaniakPressed: Color = ColorBlue700
  val ColorBackgroundBrandMailDefault: Color = ColorPink500
  val ColorBackgroundBrandMailHover: Color = ColorPink600
  val ColorBackgroundBrandMailPressed: Color = ColorPink700
  val ColorBackgroundBrandKdriveDefault: Color = ColorIndigo400
  val ColorBackgroundBrandKdriveHover: Color = ColorIndigo500
  val ColorBackgroundBrandKdrivePressed: Color = ColorIndigo600
  val ColorBackgroundBrandEuriaDefault: Color = ColorOcean700
  val ColorBackgroundBrandEuriaHover: Color = ColorOcean800
  val ColorBackgroundBrandEuriaPressed: Color = ColorOcean900
  val ColorBackgroundBrandKchatDefault: Color = ColorCyan400
  val ColorBackgroundBrandKchatHover: Color = ColorCyan500
  val ColorBackgroundBrandKchatPressed: Color = ColorCyan600
  val ColorBackgroundBrandSecurityDefault: Color = ColorPurple600
  val ColorBackgroundBrandSecurityHover: Color = ColorPurple700
  val ColorBackgroundBrandSecurityPressed: Color = ColorPurple800
  val ColorBackgroundBrandCalendarDefault: Color = ColorAqua400
  val ColorBackgroundBrandCalendarHover: Color = ColorAqua500
  val ColorBackgroundBrandCalendarPressed: Color = ColorAqua600
  val ColorBackgroundBrandContactsDefault: Color = ColorViolet300
  val ColorBackgroundBrandContactsHover: Color = ColorViolet400
  val ColorBackgroundBrandContactsPressed: Color = ColorViolet500
  val ColorBackgroundBrandKnoteDefault: Color = ColorCoral500
  val ColorBackgroundBrandKnoteHover: Color = ColorCoral600
  val ColorBackgroundBrandKnotePressed: Color = ColorCoral700
  val ColorBackgroundBrandSwisstransferDefault: Color = ColorEmerald500
  val ColorBackgroundBrandSwisstransferHover: Color = ColorEmerald600
  val ColorBackgroundBrandSwisstransferPressed: Color = ColorEmerald700
  val ColorBackgroundDisabled: Color = ColorGray200
  val ColorBackgroundDatavizOrangeDim1Default: Color = ColorOrange600
  val ColorBackgroundDatavizOrangeDim1Hover: Color = ColorOrange700
  val ColorBackgroundDatavizOrangeDim1Pressed: Color = ColorOrange800
  val ColorBackgroundDatavizOrangeDim2Default: Color = ColorOrange200
  val ColorBackgroundDatavizOrangeDim2Hover: Color = ColorOrange300
  val ColorBackgroundDatavizOrangeDim2Pressed: Color = ColorOrange400
  val ColorBackgroundDatavizEmeraldDim1Default: Color = ColorEmerald600
  val ColorBackgroundDatavizEmeraldDim1Hover: Color = ColorEmerald700
  val ColorBackgroundDatavizEmeraldDim1Pressed: Color = ColorEmerald800
  val ColorBackgroundDatavizEmeraldDim2Default: Color = ColorEmerald200
  val ColorBackgroundDatavizEmeraldDim2Hover: Color = ColorEmerald300
  val ColorBackgroundDatavizEmeraldDim2Pressed: Color = ColorEmerald400
  val ColorBackgroundDatavizBlueDim1Default: Color = ColorBlue600
  val ColorBackgroundDatavizBlueDim1Hover: Color = ColorBlue700
  val ColorBackgroundDatavizBlueDim1Pressed: Color = ColorBlue800
  val ColorBackgroundDatavizBlueDim2Default: Color = ColorBlue200
  val ColorBackgroundDatavizBlueDim2Hover: Color = ColorBlue300
  val ColorBackgroundDatavizBlueDim2Pressed: Color = ColorBlue400
  val ColorBackgroundDatavizVioletDim1Default: Color = ColorViolet600
  val ColorBackgroundDatavizVioletDim1Hover: Color = ColorViolet700
  val ColorBackgroundDatavizVioletDim1Pressed: Color = ColorViolet800
  val ColorBackgroundDatavizVioletDim2Default: Color = ColorViolet200
  val ColorBackgroundDatavizVioletDim2Hover: Color = ColorViolet300
  val ColorBackgroundDatavizVioletDim2Pressed: Color = ColorViolet400
  val ColorBackgroundDatavizPurpleDim1Default: Color = ColorPurple600
  val ColorBackgroundDatavizPurpleDim1Hover: Color = ColorPurple700
  val ColorBackgroundDatavizPurpleDim1Pressed: Color = ColorPurple800
  val ColorBackgroundDatavizPurpleDim2Default: Color = ColorPurple200
  val ColorBackgroundDatavizPurpleDim2Hover: Color = ColorPurple300
  val ColorBackgroundDatavizPurpleDim2Pressed: Color = ColorPurple400
  val ColorBackgroundDatavizPinkDim1Default: Color = ColorPink600
  val ColorBackgroundDatavizPinkDim1Hover: Color = ColorPink700
  val ColorBackgroundDatavizPinkDim1Pressed: Color = ColorPink800
  val ColorBackgroundDatavizPinkDim2Default: Color = ColorPink200
  val ColorBackgroundDatavizPinkDim2Hover: Color = ColorPink300
  val ColorBackgroundDatavizPinkDim2Pressed: Color = ColorPink400
  val ColorBackgroundDatavizYellowDim1Default: Color = ColorYellow600
  val ColorBackgroundDatavizYellowDim1Hover: Color = ColorYellow700
  val ColorBackgroundDatavizYellowDim1Pressed: Color = ColorYellow800
  val ColorBackgroundDatavizYellowDim2Default: Color = ColorYellow200
  val ColorBackgroundDatavizYellowDim2Hover: Color = ColorYellow300
  val ColorBackgroundDatavizYellowDim2Pressed: Color = ColorYellow400
  val ColorBackgroundDatavizDim1Default: Color = ColorViolet600
  val ColorBackgroundDatavizDim1Hover: Color = ColorViolet700
  val ColorBackgroundDatavizDim1Pressed: Color = ColorViolet800
  val ColorBackgroundDatavizDim2Default: Color = ColorViolet200
  val ColorBackgroundDatavizDim2Hover: Color = ColorViolet300
  val ColorBackgroundDatavizDim2Pressed: Color = ColorViolet400
  val ColorTextBrandInfomaniakDefault: Color = ColorBlue700
  val ColorTextBrandInfomaniakHover: Color = ColorBlue800
  val ColorTextBrandInfomaniakPressed: Color = ColorBlue900
  val ColorTextBrandMailDefault: Color = ColorPink700
  val ColorTextBrandMailHover: Color = ColorPink800
  val ColorTextBrandMailPressed: Color = ColorPink900
  val ColorTextBrandKdriveDefault: Color = ColorIndigo600
  val ColorTextBrandKdriveHover: Color = ColorIndigo700
  val ColorTextBrandKdrivePressed: Color = ColorIndigo800
  val ColorTextBrandEuriaDefault: Color = ColorOcean600
  val ColorTextBrandEuriaHover: Color = ColorOcean700
  val ColorTextBrandEuriaPressed: Color = ColorOcean800
  val ColorTextBrandKchatDefault: Color = ColorCyan600
  val ColorTextBrandKchatHover: Color = ColorCyan700
  val ColorTextBrandKchatPressed: Color = ColorCyan800
  val ColorTextBrandSecurityDefault: Color = ColorPurple600
  val ColorTextBrandSecurityHover: Color = ColorPurple700
  val ColorTextBrandSecurityPressed: Color = ColorPurple800
  val ColorTextBrandCalendarDefault: Color = ColorAqua500
  val ColorTextBrandCalendarHover: Color = ColorAqua600
  val ColorTextBrandCalendarPressed: Color = ColorAqua700
  val ColorTextBrandContactsDefault: Color = ColorViolet500
  val ColorTextBrandContactsHover: Color = ColorViolet600
  val ColorTextBrandContactsPressed: Color = ColorViolet700
  val ColorTextBrandKnoteDefault: Color = ColorCoral600
  val ColorTextBrandKnoteHover: Color = ColorCoral700
  val ColorTextBrandKnotePressed: Color = ColorCoral800
  val ColorTextBrandSwisstransferDefault: Color = ColorEmerald600
  val ColorTextBrandSwisstransferHover: Color = ColorEmerald700
  val ColorTextBrandSwisstransferPressed: Color = ColorEmerald800
  val ColorTextPrimary: Color = ColorGray800
  val ColorTextSecondary: Color = ColorGray600
  val ColorTextTertiary: Color = ColorGray500
  val ColorTextInverse: Color = ColorGray100
  val ColorTextDisabled: Color = ColorGray400
  val ColorTextOnDatavizBlueDefault: Color = ColorBlue900
  val ColorTextOnDatavizEmeraldDefault: Color = ColorEmerald900
  val ColorTextOnDatavizOrangeDefault: Color = ColorOrange900
  val ColorTextOnDatavizPinkDefault: Color = ColorPink900
  val ColorTextOnDatavizPurpleDefault: Color = ColorPurple900
  val ColorTextOnDatavizVioletDefault: Color = ColorViolet900
  val ColorTextOnDatavizYellowDefault: Color = ColorYellow900
  val ColorTextOnDatavizDefault: Color = ColorViolet900
  val ColorTextOnBrandInfomaniakDefault: Color = ColorBlue950
  val ColorTextOnBrandCalendarDefault: Color = ColorAqua950
  val ColorTextOnBrandContactsDefault: Color = ColorViolet950
  val ColorTextOnBrandEuriaDefault: Color = ColorOcean50
  val ColorTextOnBrandKchatDefault: Color = ColorCyan950
  val ColorTextOnBrandKdriveDefault: Color = ColorIndigo50
  val ColorTextOnBrandKnoteDefault: Color = ColorCoral50
  val ColorTextOnBrandMailDefault: Color = ColorPink50
  val ColorTextOnBrandSecurityDefault: Color = ColorPurple50
  val ColorTextOnBrandSwisstransferDefault: Color = ColorEmerald950
  val ColorTextOnDisabled: Color = ColorGray400
  val ColorTextOnFeedbackWarningDim2: Color = ColorOrange950
  val ColorTextOnFeedbackWarningDim1: Color = ColorOrange900
  val ColorTextOnFeedbackSuccessDim2: Color = ColorLime50
  val ColorTextOnFeedbackSuccessDim1: Color = ColorLime950
  val ColorTextOnFeedbackErrorDim2: Color = ColorRed50
  val ColorTextOnFeedbackErrorDim1: Color = ColorRed900
  val ColorTextFeedbackErrorDefault: Color = ColorRed700
  val ColorTextFeedbackErrorHover: Color = ColorRed800
  val ColorTextFeedbackErrorPressed: Color = ColorRed900
  val ColorTextFeedbackSuccessDefault: Color = ColorLime700
  val ColorTextFeedbackSuccessHover: Color = ColorLime800
  val ColorTextFeedbackSuccessPressed: Color = ColorLime900
  val ColorTextFeedbackWarningDefault: Color = ColorOrange700
  val ColorTextFeedbackWarningHover: Color = ColorOrange800
  val ColorTextFeedbackWarningPressed: Color = ColorOrange900
  val ColorBorderDim1Default: Color = ColorGray400
  val ColorBorderDim1Hover: Color = ColorGray500
  val ColorBorderDim1Pressed: Color = ColorGray600
  val ColorBorderBrandInfomaniakDefault: Color = ColorBlue500
  val ColorBorderBrandInfomaniakHover: Color = ColorBlue600
  val ColorBorderBrandInfomaniakPressed: Color = ColorBlue700
  val ColorBorderBrandMailDefault: Color = ColorPink500
  val ColorBorderBrandMailHover: Color = ColorPink600
  val ColorBorderBrandMailPressed: Color = ColorPink700
  val ColorBorderBrandKdriveDefault: Color = ColorIndigo400
  val ColorBorderBrandKdriveHover: Color = ColorIndigo500
  val ColorBorderBrandKdrivePressed: Color = ColorIndigo600
  val ColorBorderBrandEuriaDefault: Color = ColorOcean600
  val ColorBorderBrandEuriaHover: Color = ColorOcean700
  val ColorBorderBrandEuriaPressed: Color = ColorOcean800
  val ColorBorderBrandKchatDefault: Color = ColorCyan400
  val ColorBorderBrandKchatHover: Color = ColorCyan500
  val ColorBorderBrandKchatPressed: Color = ColorCyan600
  val ColorBorderBrandSecurityDefault: Color = ColorPurple600
  val ColorBorderBrandSecurityHover: Color = ColorPurple700
  val ColorBorderBrandSecurityPressed: Color = ColorPurple800
  val ColorBorderBrandCalendarDefault: Color = ColorAqua400
  val ColorBorderBrandCalendarHover: Color = ColorAqua500
  val ColorBorderBrandCalendarPressed: Color = ColorAqua600
  val ColorBorderBrandContactsDefault: Color = ColorViolet300
  val ColorBorderBrandContactsHover: Color = ColorViolet400
  val ColorBorderBrandContactsPressed: Color = ColorViolet500
  val ColorBorderBrandKnoteDefault: Color = ColorCoral400
  val ColorBorderBrandKnoteHover: Color = ColorCoral500
  val ColorBorderBrandKnotePressed: Color = ColorCoral600
  val ColorBorderBrandSwisstransferDefault: Color = ColorEmerald500
  val ColorBorderBrandSwisstransferHover: Color = ColorEmerald600
  val ColorBorderBrandSwisstransferPressed: Color = ColorEmerald700
  val ColorBorderDatavizBlueDim1Default: Color = ColorBlue600
  val ColorBorderDatavizBlueDim1Hover: Color = ColorBlue700
  val ColorBorderDatavizBlueDim1Pressed: Color = ColorBlue800
  val ColorBorderDatavizBlueDim2Default: Color = ColorBlue200
  val ColorBorderDatavizBlueDim2Hover: Color = ColorBlue300
  val ColorBorderDatavizBlueDim2Pressed: Color = ColorBlue400
  val ColorBorderDatavizEmeraldDim1Default: Color = ColorEmerald600
  val ColorBorderDatavizEmeraldDim1Hover: Color = ColorEmerald700
  val ColorBorderDatavizEmeraldDim1Pressed: Color = ColorEmerald800
  val ColorBorderDatavizEmeraldDim2Default: Color = ColorEmerald200
  val ColorBorderDatavizEmeraldDim2Hover: Color = ColorEmerald300
  val ColorBorderDatavizEmeraldDim2Pressed: Color = ColorEmerald400
  val ColorBorderDatavizOrangeDim1Default: Color = ColorOrange600
  val ColorBorderDatavizOrangeDim1Hover: Color = ColorOrange700
  val ColorBorderDatavizOrangeDim1Pressed: Color = ColorOrange800
  val ColorBorderDatavizOrangeDim2Default: Color = ColorOrange200
  val ColorBorderDatavizOrangeDim2Hover: Color = ColorOrange300
  val ColorBorderDatavizOrangeDim2Pressed: Color = ColorOrange400
  val ColorBorderDatavizPinkDim1Default: Color = ColorPink600
  val ColorBorderDatavizPinkDim1Hover: Color = ColorPink700
  val ColorBorderDatavizPinkDim1Pressed: Color = ColorPink800
  val ColorBorderDatavizPinkDim2Default: Color = ColorPink200
  val ColorBorderDatavizPinkDim2Hover: Color = ColorPink300
  val ColorBorderDatavizPinkDim2Pressed: Color = ColorPink400
  val ColorBorderDatavizPurpleDim1Default: Color = ColorPurple600
  val ColorBorderDatavizPurpleDim1Hover: Color = ColorPurple700
  val ColorBorderDatavizPurpleDim1Pressed: Color = ColorPurple800
  val ColorBorderDatavizPurpleDim2Default: Color = ColorPurple200
  val ColorBorderDatavizPurpleDim2Hover: Color = ColorPurple300
  val ColorBorderDatavizPurpleDim2Pressed: Color = ColorPurple400
  val ColorBorderDatavizVioletDim1Default: Color = ColorViolet600
  val ColorBorderDatavizVioletDim1Hover: Color = ColorViolet700
  val ColorBorderDatavizVioletDim1Pressed: Color = ColorViolet800
  val ColorBorderDatavizVioletDim2Default: Color = ColorViolet200
  val ColorBorderDatavizVioletDim2Hover: Color = ColorViolet300
  val ColorBorderDatavizVioletDim2Pressed: Color = ColorViolet400
  val ColorBorderDatavizYellowDim1Default: Color = ColorYellow600
  val ColorBorderDatavizYellowDim1Hover: Color = ColorYellow700
  val ColorBorderDatavizYellowDim1Pressed: Color = ColorYellow800
  val ColorBorderDatavizYellowDim2Default: Color = ColorYellow200
  val ColorBorderDatavizYellowDim2Hover: Color = ColorYellow300
  val ColorBorderDatavizYellowDim2Pressed: Color = ColorYellow400
  val ColorBorderDatavizDim1Default: Color = ColorViolet600
  val ColorBorderDatavizDim1Hover: Color = ColorViolet700
  val ColorBorderDatavizDim1Pressed: Color = ColorViolet800
  val ColorBorderDatavizDim2Default: Color = ColorViolet200
  val ColorBorderDatavizDim2Hover: Color = ColorViolet300
  val ColorBorderDatavizDim2Pressed: Color = ColorViolet400
  val ColorBorderFeedbackErrorDim1Default: Color = ColorRed600
  val ColorBorderFeedbackErrorDim1Hover: Color = ColorRed700
  val ColorBorderFeedbackErrorDim1Pressed: Color = ColorRed800
  val ColorBorderFeedbackErrorDim2Default: Color = ColorRed200
  val ColorBorderFeedbackErrorDim2Hover: Color = ColorRed300
  val ColorBorderFeedbackErrorDim2Pressed: Color = ColorRed400
  val ColorBorderFeedbackSuccessDim1Default: Color = ColorLime600
  val ColorBorderFeedbackSuccessDim1Hover: Color = ColorLime700
  val ColorBorderFeedbackSuccessDim1Pressed: Color = ColorLime800
  val ColorBorderFeedbackSuccessDim2Default: Color = ColorLime200
  val ColorBorderFeedbackSuccessDim2Hover: Color = ColorLime300
  val ColorBorderFeedbackSuccessDim2Pressed: Color = ColorLime400
  val ColorBorderFeedbackWarningDim1Default: Color = ColorOrange600
  val ColorBorderFeedbackWarningDim1Hover: Color = ColorOrange700
  val ColorBorderFeedbackWarningDim1Pressed: Color = ColorOrange800
  val ColorBorderFeedbackWarningDim2Default: Color = ColorOrange200
  val ColorBorderFeedbackWarningDim2Hover: Color = ColorOrange300
  val ColorBorderFeedbackWarningDim2Pressed: Color = ColorOrange400
  val ColorBorderDim2Default: Color = ColorGray300
  val ColorBorderDim2Hover: Color = ColorGray400
  val ColorBorderDim2Pressed: Color = ColorGray500
  val ColorBorderDim3Default: Color = ColorGray200
  val ColorBorderDim3Hover: Color = ColorGray300
  val ColorBorderDim3Pressed: Color = ColorGray400
  val ColorBorderDim4Default: Color = ColorGray100
  val ColorBorderDim4Hover: Color = ColorGray200
  val ColorBorderDim4Pressed: Color = ColorGray300
  val ColorShadowXs: Color = ColorTransparent
  val ColorShadowSm: Color = ColorGray4006
  val ColorShadowMd: Color = ColorGray4008
  val ColorShadowLg: Color = ColorGray40010
  val ColorShadowXl: Color = ColorGray40010
  val ColorShadow2xl: Color = ColorGray40014
  val ColorIconBrandInfomaniakDefault: Color = ColorBlue600
  val ColorIconBrandInfomaniakHover: Color = ColorBlue700
  val ColorIconBrandInfomaniakPressed: Color = ColorBlue800
  val ColorIconBrandMailDefault: Color = ColorPink600
  val ColorIconBrandMailHover: Color = ColorPink700
  val ColorIconBrandMailPressed: Color = ColorPink800
  val ColorIconBrandKdriveDefault: Color = ColorIndigo600
  val ColorIconBrandKdriveHover: Color = ColorIndigo700
  val ColorIconBrandKdrivePressed: Color = ColorIndigo800
  val ColorIconBrandEuriaDefault: Color = ColorOcean600
  val ColorIconBrandEuriaHover: Color = ColorOcean700
  val ColorIconBrandEuriaPressed: Color = ColorOcean800
  val ColorIconBrandKchatDefault: Color = ColorCyan600
  val ColorIconBrandKchatHover: Color = ColorCyan700
  val ColorIconBrandKchatPressed: Color = ColorCyan800
  val ColorIconBrandSecurityDefault: Color = ColorPurple600
  val ColorIconBrandSecurityHover: Color = ColorPurple700
  val ColorIconBrandSecurityPressed: Color = ColorPurple800
  val ColorIconBrandCalendarDefault: Color = ColorAqua600
  val ColorIconBrandCalendarHover: Color = ColorAqua700
  val ColorIconBrandCalendarPressed: Color = ColorAqua800
  val ColorIconBrandContactsDefault: Color = ColorViolet600
  val ColorIconBrandContactsHover: Color = ColorViolet700
  val ColorIconBrandContactsPressed: Color = ColorViolet800
  val ColorIconBrandKnoteDefault: Color = ColorCoral600
  val ColorIconBrandKnoteHover: Color = ColorCoral700
  val ColorIconBrandKnotePressed: Color = ColorCoral800
  val ColorIconBrandSwisstransferDefault: Color = ColorEmerald600
  val ColorIconBrandSwisstransferHover: Color = ColorEmerald700
  val ColorIconBrandSwisstransferPressed: Color = ColorEmerald800
  val ColorIconPrimary: Color = ColorGray800
  val ColorIconSecondary: Color = ColorGray600
  val ColorIconTertiary: Color = ColorGray500
  val ColorIconInverse: Color = ColorGray100
  val ColorIconDisabled: Color = ColorGray400
  val ColorIconOnDisabled: Color = ColorGray400
  val ColorIconOnDatavizBlueDefault: Color = ColorBlue800
  val ColorIconOnDatavizEmeraldDefault: Color = ColorEmerald800
  val ColorIconOnDatavizOrangeDefault: Color = ColorOrange800
  val ColorIconOnDatavizPinkDefault: Color = ColorPink800
  val ColorIconOnDatavizPurpleDefault: Color = ColorPurple800
  val ColorIconOnDatavizVioletDefault: Color = ColorViolet800
  val ColorIconOnDatavizYellowDefault: Color = ColorYellow800
  val ColorIconOnDatavizDefault: Color = ColorViolet800
  val ColorIconOnBrandInfomaniakDefault: Color = ColorBlue950
  val ColorIconOnBrandCalendarDefault: Color = ColorBlue950
  val ColorIconOnBrandContactsDefault: Color = ColorBlue950
  val ColorIconOnBrandEuriaDefault: Color = ColorOcean50
  val ColorIconOnBrandKchatDefault: Color = ColorBlue950
  val ColorIconOnBrandKdriveDefault: Color = ColorIndigo50
  val ColorIconOnBrandKnoteDefault: Color = ColorCoral50
  val ColorIconOnBrandMailDefault: Color = ColorPink50
  val ColorIconOnBrandSecurityDefault: Color = ColorPurple50
  val ColorIconOnBrandSwisstransferDefault: Color = ColorBlue950
  val ColorIconOnFeedbackSuccessDim2: Color = ColorLime50
  val ColorIconOnFeedbackSuccessDim1: Color = ColorLime950
  val ColorIconOnFeedbackWarningDim2: Color = ColorOrange950
  val ColorIconOnFeedbackWarningDim1: Color = ColorOrange900
  val ColorIconOnFeedbackErrorDim2: Color = ColorRed50
  val ColorIconOnFeedbackErrorDim1: Color = ColorRed900
  val ColorIconFeedbackErrorDefault: Color = ColorRed700
  val ColorIconFeedbackErrorHover: Color = ColorRed800
  val ColorIconFeedbackErrorPressed: Color = ColorRed900
  val ColorIconFeedbackSuccessDefault: Color = ColorLime700
  val ColorIconFeedbackSuccessHover: Color = ColorLime800
  val ColorIconFeedbackSuccessPressed: Color = ColorLime900
  val ColorIconFeedbackWarningDefault: Color = ColorOrange700
  val ColorIconFeedbackWarningHover: Color = ColorOrange800
  val ColorIconFeedbackWarningPressed: Color = ColorOrange900
  val FontSizeXs: TextUnit = FontSize12
  val FontSizeSm: TextUnit = FontSize14
  val FontSizeMd: TextUnit = FontSize16
  val FontSizeLg: TextUnit = FontSize18
  val FontSizeXl: TextUnit = FontSize20
  val FontSize2xl: TextUnit = FontSize24
  val FontSize3xl: TextUnit = FontSize32
  val FontSize4xl: TextUnit = FontSize40
  val FontSize5xl: TextUnit = FontSize48
  val FontFamilyBase: FontFamily = FontFamilySuisseIntL
  val FontLineHeightXs: TextUnit = FontLineHeight16
  val FontLineHeightSm: TextUnit = FontLineHeight20
  val FontLineHeightMd: TextUnit = FontLineHeight24
  val FontLineHeightXl: TextUnit = FontLineHeight28
  val FontLineHeight2xl: TextUnit = FontLineHeight32
  val FontLineHeight3xl: TextUnit = FontLineHeight40
  val FontLineHeight4xl: TextUnit = FontLineHeight48
  val FontLineHeight5xl: TextUnit = FontLineHeight56
  val FontLineHeightLg: TextUnit = FontLineHeight26
  val FontLetterSpacingMd: TextUnit = FontLetterSpacing0
  val FontWeightRegular: FontWeight = FontWeight400
  val FontWeightMedium: FontWeight = FontWeight500
  val IconSizeXs: Dp = Scale16
  val IconSizeMd: Dp = Scale24
  val IconSizeLg: Dp = Scale32
  val IconSizeSm: Dp = Scale20
  val IconSizeXl: Dp = Scale40
  val OpacityNone: Float = Opacity0
  val OpacityGhost: Float = Opacity5
  val OpacitySubtle: Float = Opacity10
  val OpacitySoft: Float = Opacity25
  val OpacityMedium: Float = Opacity50
  val OpacityStrong: Float = Opacity75
  val OpacityHeavy: Float = Opacity90
  val OpacityFull: Float = Opacity100
  val RadiusNone: Shape = Radius0
  val RadiusXs: Shape = Radius2
  val RadiusSm: Shape = Radius4
  val RadiusMd: Shape = Radius6
  val RadiusLg: Shape = Radius8
  val RadiusXl: Shape = Radius12
  val Radius2xl: Shape = Radius16
  val Radius3xl: Shape = Radius24
  val Radius4xl: Shape = Radius32
  val RadiusFull: Shape = Radius1000
  val ShadowXsX: Dp = Shadow1X
  val ShadowXsY: Dp = Shadow1Y
  val ShadowXsBlur: Dp = Shadow1Blur
  val ShadowXsSpread: Dp = Shadow1Spread
  val ShadowSmX: Dp = Shadow2X
  val ShadowSmY: Dp = Shadow2Y
  val ShadowSmBlur: Dp = Shadow2Blur
  val ShadowSmSpread: Dp = Shadow2Spread
  val ShadowMdX: Dp = Shadow3X
  val ShadowMdY: Dp = Shadow3Y
  val ShadowMdBlur: Dp = Shadow3Blur
  val ShadowMdSpread: Dp = Shadow3Spread
  val ShadowLgX: Dp = Shadow4X
  val ShadowLgY: Dp = Shadow4Y
  val ShadowLgBlur: Dp = Shadow4Blur
  val ShadowLgSpread: Dp = Shadow4Spread
  val ShadowXlX: Dp = Shadow5X
  val ShadowXlY: Dp = Shadow5Y
  val ShadowXlBlur: Dp = Shadow5Blur
  val ShadowXlSpread: Dp = Shadow5Spread
  val Shadow2xlX: Dp = Shadow6X
  val Shadow2xlY: Dp = Shadow6Y
  val Shadow2xlBlur: Dp = Shadow6Blur
  val Shadow2xlSpread: Dp = Shadow6Spread
  val SpacingNone: Dp = Spacing0
  val Spacing2xs: Dp = Spacing2
  val SpacingXs: Dp = Spacing4
  val SpacingSm: Dp = Spacing6
  val SpacingMd: Dp = Spacing8
  val SpacingLg: Dp = Spacing12
  val SpacingXl: Dp = Spacing16
  val Spacing2xl: Dp = Spacing20
  val Spacing3xl: Dp = Spacing24
  val Spacing4xl: Dp = Spacing32
  val Spacing5xl: Dp = Spacing40
  val Spacing6xl: Dp = Spacing48
  val Spacing7xl: Dp = Spacing64
  val Spacing8xl: Dp = Spacing100
  val TextXsSize: TextUnit = FontSizeXs
  val TextXsLineHeight: TextUnit = FontLineHeightXs
  val TextXsLetterSpacing: TextUnit = FontLetterSpacingMd
  val TextSmSize: TextUnit = FontSizeSm
  val TextSmLineHeight: TextUnit = FontLineHeightSm
  val TextSmLetterSpacing: TextUnit = FontLetterSpacingMd
  val TextMdSize: TextUnit = FontSizeMd
  val TextMdLineHeight: TextUnit = FontLineHeightMd
  val TextMdLetterSpacing: TextUnit = FontLetterSpacingMd
  val TextLgSize: TextUnit = FontSizeLg
  val TextLgLineHeight: TextUnit = FontLineHeightLg
  val TextLgLetterSpacing: TextUnit = FontLetterSpacingMd
  val TextXlSize: TextUnit = FontSizeXl
  val TextXlLineHeight: TextUnit = FontLineHeightXl
  val TextXlLetterSpacing: TextUnit = FontLetterSpacingMd
  val Text2xlSize: TextUnit = FontSize2xl
  val Text2xlLineHeight: TextUnit = FontLineHeight2xl
  val Text2xlLetterSpacing: TextUnit = FontLetterSpacingMd
  val Text3xlSize: TextUnit = FontSize3xl
  val Text3xlLineHeight: TextUnit = FontLineHeight3xl
  val Text3xlLetterSpacing: TextUnit = FontLetterSpacingMd
  val Text4xlSize: TextUnit = FontSize4xl
  val Text4xlLineHeight: TextUnit = FontLineHeight4xl
  val Text4xlLetterSpacing: TextUnit = FontLetterSpacingMd
  val Text5xlSize: TextUnit = FontSize5xl
  val Text5xlLineHeight: TextUnit = FontLineHeight5xl
  val Text5xlLetterSpacing: TextUnit = FontLetterSpacingMd
  val TypographyDisplayMdBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = Text5xlSize,
    letterSpacing = Text5xlLetterSpacing,
    lineHeight = Text5xlLineHeight,
  )
  val TypographyDisplayMdEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = Text5xlSize,
    letterSpacing = Text5xlLetterSpacing,
    lineHeight = Text5xlLineHeight,
  )
  val TypographyHeadingLgBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = Text4xlSize,
    letterSpacing = Text4xlLetterSpacing,
    lineHeight = Text4xlLineHeight,
  )
  val TypographyHeadingLgEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = Text4xlSize,
    letterSpacing = Text4xlLetterSpacing,
    lineHeight = Text4xlLineHeight,
  )
  val TypographyHeadingMdBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = Text3xlSize,
    letterSpacing = Text3xlLetterSpacing,
    lineHeight = Text3xlLineHeight,
  )
  val TypographyHeadingMdEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = Text3xlSize,
    letterSpacing = Text3xlLetterSpacing,
    lineHeight = Text3xlLineHeight,
  )
  val TypographyHeadingSmBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = Text2xlSize,
    letterSpacing = Text2xlLetterSpacing,
    lineHeight = Text2xlLineHeight,
  )
  val TypographyHeadingSmEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = Text2xlSize,
    letterSpacing = Text2xlLetterSpacing,
    lineHeight = Text2xlLineHeight,
  )
  val TypographyTitleMdBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = TextXlSize,
    letterSpacing = TextXlLetterSpacing,
    lineHeight = TextXlLineHeight,
  )
  val TypographyTitleMdEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = TextXlSize,
    letterSpacing = TextXlLetterSpacing,
    lineHeight = TextXlLineHeight,
  )
  val TypographyBodyLgBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = TextLgSize,
    letterSpacing = TextLgLetterSpacing,
    lineHeight = TextLgLineHeight,
  )
  val TypographyBodyLgEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = TextLgSize,
    letterSpacing = TextLgLetterSpacing,
    lineHeight = TextLgLineHeight,
  )
  val TypographyBodyMdBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = TextMdSize,
    letterSpacing = TextMdLetterSpacing,
    lineHeight = TextMdLineHeight,
  )
  val TypographyBodyMdEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = TextMdSize,
    letterSpacing = TextMdLetterSpacing,
    lineHeight = TextMdLineHeight,
  )
  val TypographyBodySmBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = TextSmSize,
    letterSpacing = TextSmLetterSpacing,
    lineHeight = TextSmLineHeight,
  )
  val TypographyBodySmEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = TextSmSize,
    letterSpacing = TextSmLetterSpacing,
    lineHeight = TextSmLineHeight,
  )
  val TypographyCaptionMdBase: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightRegular,
    fontSize = TextXsSize,
    letterSpacing = TextXsLetterSpacing,
    lineHeight = TextXsLineHeight,
  )
  val TypographyCaptionMdEmphasized: TextStyle = TextStyle(
    fontFamily = FontFamilyBase,
    fontWeight = FontWeightMedium,
    fontSize = TextXsSize,
    letterSpacing = TextXsLetterSpacing,
    lineHeight = TextXsLineHeight,
  )
  val ColorBackgroundBrandDefault: Color = ColorBackgroundBrandSwisstransferDefault
  val ColorBackgroundBrandHover: Color = ColorBackgroundBrandSwisstransferHover
  val ColorBackgroundBrandPressed: Color = ColorBackgroundBrandSwisstransferPressed
  val ColorTextBrandDefault: Color = ColorTextBrandSwisstransferDefault
  val ColorTextBrandHover: Color = ColorTextBrandSwisstransferHover
  val ColorTextBrandPressed: Color = ColorTextBrandSwisstransferPressed
  val ColorTextOnBrandDefault: Color = ColorTextOnBrandSwisstransferDefault
  val ColorIconBrandDefault: Color = ColorIconBrandSwisstransferDefault
  val ColorIconBrandHover: Color = ColorIconBrandSwisstransferHover
  val ColorIconBrandPressed: Color = ColorIconBrandSwisstransferPressed
  val ColorIconOnBrandDefault: Color = ColorIconOnBrandSwisstransferDefault
  val ColorBorderBrandDefault: Color = ColorBorderBrandSwisstransferDefault
  val ColorBorderBrandHover: Color = ColorBorderBrandSwisstransferHover
  val ColorBorderBrandPressed: Color = ColorBorderBrandSwisstransferPressed
}