/*
  To generate
*/

package com.infomaniak.designsystem.core.tokens

import androidx.compose.ui.graphics.Color
import com.infomaniak.designsystem.primitivetokens.*

data class ColorTokens(
    val backgroundElevationSurfacePressed: Color = ColorRed500,
    val backgroundElevationSurfaceHover: Color = ColorRed500,
    val backgroundElevationSurfaceDefault: Color = ColorRed500,
    val backgroundElevationOverlayDefault: Color = ColorRed500,
    val backgroundElevationOverlayHover: Color = ColorRed500,
    val backgroundElevationOverlayPressed: Color = ColorRed500,
    val backgroundElevationRaisedDefault: Color = ColorRed500,
    val backgroundElevationRaisedHover: Color = ColorRed500,
    val backgroundElevationRaisedPressed: Color = ColorRed500,
    val backgroundErrorDefault: Color = ColorRed500,
    val backgroundErrorHover: Color = ColorRed500,
    val backgroundErrorPressed: Color = ColorRed500,
    val backgroundWarningDefault: Color = ColorRed500,
    val backgroundWarningHover: Color = ColorRed500,
    val backgroundWarningPressed: Color = ColorRed500,
    val backgroundBrandInfomaniakDefault: Color = ColorRed500,
    val backgroundBrandInfomaniakHover: Color = ColorRed500,
    val backgroundBrandInfomaniakPressed: Color = ColorRed500,
    val backgroundBrandMailDefault: Color = ColorRed500,
    val backgroundBrandMailHover: Color = ColorRed500,
    val backgroundBrandMailPressed: Color = ColorRed500,
    val backgroundBrandKdriveDefault: Color = ColorRed500,
    val backgroundBrandKdriveHover: Color = ColorRed500,
    val backgroundBrandKdrivePressed: Color = ColorRed500,
    val backgroundBrandEuriaDefault: Color = ColorRed500,
    val backgroundBrandEuriaHover: Color = ColorRed500,
    val backgroundBrandEuriaPressed: Color = ColorRed500,
    val backgroundBrandKchatDefault: Color = ColorRed500,
    val backgroundBrandKchatHover: Color = ColorRed500,
    val backgroundBrandKchatPressed: Color = ColorRed500,
    val backgroundBrandSecurityDefault: Color = ColorRed500,
    val backgroundBrandSecurityHover: Color = ColorRed500,
    val backgroundBrandSecurityPressed: Color = ColorRed500,
    val backgroundBrandCalendarDefault: Color = ColorRed500,
    val backgroundBrandCalendarHover: Color = ColorRed500,
    val backgroundBrandCalendarPressed: Color = ColorRed500,
    val backgroundBrandContactsDefault: Color = ColorRed500,
    val backgroundBrandContactsHover: Color = ColorRed500,
    val backgroundBrandContactsPressed: Color = ColorRed500,
    val backgroundBrandKnoteDefault: Color = ColorRed500,
    val backgroundBrandKnoteHover: Color = ColorRed500,
    val backgroundBrandKnotePressed: Color = ColorRed500,
    val backgroundBrandSwisstransferDefault: Color = ColorRed500,
    val backgroundBrandSwisstransferHover: Color = ColorRed500,
    val backgroundBrandSwisstransferPressed: Color = ColorRed500,
    val backgroundBrandDefault: Color = ColorRed500,
    val backgroundBrandPressed: Color = ColorRed500,
    val backgroundBrandHover: Color = ColorRed500,
    val backgroundSuccessDefault: Color = ColorRed500,
    val backgroundSuccessHover: Color = ColorRed500,
    val backgroundSuccessPressed: Color = ColorRed500,
    val backgroundNeutralDefault: Color = ColorRed500,
    val backgroundNeutralHover: Color = ColorRed500,
    val backgroundNeutralPressed: Color = ColorRed500,
    val textBrandInfomaniakDefault: Color = ColorRed500,
    val textBrandInfomaniakHover: Color = ColorRed500,
    val textBrandInfomaniakPressed: Color = ColorRed500,
    val textBrandMailDefault: Color = ColorRed500,
    val textBrandMailHover: Color = ColorRed500,
    val textBrandMailPressed: Color = ColorRed500,
    val textBrandKdriveDefault: Color = ColorRed500,
    val textBrandKdriveHover: Color = ColorRed500,
    val textBrandKdrivePressed: Color = ColorRed500,
    val textBrandEuriaDefault: Color = ColorRed500,
    val textBrandEuriaHover: Color = ColorRed500,
    val textBrandEuriaPressed: Color = ColorRed500,
    val textBrandKchatDefault: Color = ColorRed500,
    val textBrandKchatHover: Color = ColorRed500,
    val textBrandKchatPressed: Color = ColorRed500,
    val textBrandSecurityDefault: Color = ColorRed500,
    val textBrandSecurityHover: Color = ColorRed500,
    val textBrandSecurityPressed: Color = ColorRed500,
    val textBrandCalendarDefault: Color = ColorRed500,
    val textBrandCalendarHover: Color = ColorRed500,
    val textBrandCalendarPressed: Color = ColorRed500,
    val textBrandContactsDefault: Color = ColorRed500,
    val textBrandContactsHover: Color = ColorRed500,
    val textBrandContactsPressed: Color = ColorRed500,
    val textBrandKnoteDefault: Color = ColorRed500,
    val textBrandKnoteHover: Color = ColorRed500,
    val textBrandKnotePressed: Color = ColorRed500,
    val textBrandSwisstransferDefault: Color = ColorRed500,
    val textBrandSwisstransferHover: Color = ColorRed500,
    val textBrandSwisstransferPressed: Color = ColorRed500,
    val textBrandDefault: Color = ColorRed500,
    val textBrandHover: Color = ColorRed500,
    val textBrandPressed: Color = ColorRed500,
    val textPrimary: Color = ColorRed500,
    val textSecondary: Color = ColorRed500,
    val textTertiary: Color = ColorRed500,
    val textInverse: Color = ColorRed500,
    val textDisabled: Color = ColorRed500,
    val borderStrongDefault: Color = ColorRed500,
    val borderStrongHover: Color = ColorRed500,
    val borderStrongPressed: Color = ColorRed500,
    val borderSubtleDefault: Color = ColorRed500,
    val borderSubtleHover: Color = ColorRed500,
    val borderSubtlePressed: Color = ColorRed500,
    val borderSubtlestDefault: Color = ColorRed500,
    val borderSubtlestHover: Color = ColorRed500,
    val borderSubtlestPressed: Color = ColorRed500,
)
